# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Studia_magisterksie/Semestr_1/Systemy_dedykowane_w_ukladach_programowalnych/Sobel_Filter/Sobel_filter_rtl/Sobel_filter.srcs/sources_1/bd/rgb_design/ip/rgb_design_xbar_1/rgb_design_xbar_1.xci
# IP: The module: 'rgb_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Studia_magisterksie/Semestr_1/Systemy_dedykowane_w_ukladach_programowalnych/Sobel_Filter/Sobel_filter_rtl/Sobel_filter.gen/sources_1/bd/rgb_design/ip/rgb_design_xbar_1/rgb_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_design_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Studia_magisterksie/Semestr_1/Systemy_dedykowane_w_ukladach_programowalnych/Sobel_Filter/Sobel_filter_rtl/Sobel_filter.srcs/sources_1/bd/rgb_design/ip/rgb_design_xbar_1/rgb_design_xbar_1.xci
# IP: The module: 'rgb_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Studia_magisterksie/Semestr_1/Systemy_dedykowane_w_ukladach_programowalnych/Sobel_Filter/Sobel_filter_rtl/Sobel_filter.gen/sources_1/bd/rgb_design/ip/rgb_design_xbar_1/rgb_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_design_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
