# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sobel_design/sobel_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design || ORIG_REF_NAME==sobel_design} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_zynq_ultra_ps_e_0_0/sobel_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==sobel_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_axi_dma_0_0/sobel_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_axi_dma_0_0 || ORIG_REF_NAME==sobel_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_axi_interconnect_0_0/sobel_design_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_axi_interconnect_0_0 || ORIG_REF_NAME==sobel_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_xbar_1/sobel_design_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_xbar_1 || ORIG_REF_NAME==sobel_design_xbar_1} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_axi_interconnect_1_0/sobel_design_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_axi_interconnect_1_0 || ORIG_REF_NAME==sobel_design_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_rst_ps8_0_99M_0/sobel_design_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_rst_ps8_0_99M_0 || ORIG_REF_NAME==sobel_design_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_sobel_ip_0_2/sobel_design_sobel_ip_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_sobel_ip_0_2 || ORIG_REF_NAME==sobel_design_sobel_ip_0_2} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_auto_ds_0/sobel_design_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_auto_ds_0 || ORIG_REF_NAME==sobel_design_auto_ds_0} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_auto_pc_0/sobel_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_auto_pc_0 || ORIG_REF_NAME==sobel_design_auto_pc_0} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_auto_us_0/sobel_design_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_auto_us_0 || ORIG_REF_NAME==sobel_design_auto_us_0} -quiet] -quiet

# IP: bd/sobel_design/ip/sobel_design_auto_us_1/sobel_design_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sobel_design_auto_us_1 || ORIG_REF_NAME==sobel_design_auto_us_1} -quiet] -quiet

# XDC: c:/Studia_magisterksie/Semestr_1/Systemy_dedykowane_w_ukladach_programowalnych/Sobel_Filter/Sobel_filter_rtl/Sobel_filter.gen/sources_1/bd/sobel_design/sobel_design_ooc.xdc
